name: CI

on: [push]

jobs:
  checkCommit:
    runs-on: ubuntu-latest
    steps:
      - name: print github object
        run: echo "${{ github.event.action }}"
      - name: step 2a
        if: github.event.pull_request.merged == true
        run: echo "commit has 2 parents, $commitid is a merge commit"
      - name: step 2b
        if: github.event.pull_request.merged == false
        run: echo "commit $commitid is a simple commit"