name: CI

on: [push]

jobs:
  checkCommit:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "Hello, world!"
      - name: step 2a
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: echo "commit has 2 parents, $commitid is a merge commit"
      - name: step 2b
        if: github.event_name != 'pull_request'  && github.event.action != 'closed'
        run: echo "commit $commitid is a simple commit"